image: hhucn/dbas-build

.job-template: &job-definition
  services:
    - hhucn/docker-dbas-postgres
  before_script:
    - export PIP_CACHE_DIR="pip-cache"
    - pip install --quiet -U pip
    - pip install --quiet -r requirements.txt
    - python setup.py --quiet develop
    - cp docker.ini development.ini
    - initialize_discussion_sql development.ini > /dev/null 2>&1
    - initialize_news_sql development.ini > /dev/null 2>&1
    - init_discussion_testvotes development.ini > /dev/null 2>&1
    - init_review_tests development.ini > /dev/null 2>&1

flake8:
  stage: test
  script:
    - pip install --quiet flake8
    - flake8 .
  allow_failure: true

unit-test:
  <<: *job-definition
  stage: test
  script:
    - nosetests -v -w $(pwd) dbas graph admin api export

#function-test:
#  <<: *job-definition
#  stage: test
#  script:
#    - pserve development.ini --daemon
#    - sleep 10
#    - python tests/splinterTests.py --no-input
#  allow_failure: true

nose-acceptance-tests:
  <<: *job-definition
  stage: test
  script:
    - pserve development.ini --daemon
    - sleep 10
    - nosetests -v --process-timeout=120 tests/test_frontend
