image: hhucn/dbas-build

variables:
  INIFILE: "docker.ini"

.job-template: &job-definition
  services:
    - hhucn/docker-dbas-postgres
  before_script:
    - pip install --quiet -U pip
    - pip install --quiet -r requirements.txt
    - python setup.py --quiet develop
    - initialize_discussion_sql $INIFILE > /dev/null 2>&1
    - initialize_news_sql $INIFILE > /dev/null 2>&1
    - init_discussion_testvotes $INIFILE > /dev/null 2>&1
    - init_review_tests $INIFILE > /dev/null 2>&1

start-server:
  <<: *job-definition
  stage: build
  script:
    - pserve development.ini --daemon
    - pserve development.ini --status

flake8:
  stage: build
  script:
    - pip install --quiet flake8
    - flake8 .
  allow_failure: true

unit:
  <<: *job-definition
  stage: test
  script:
    - nosetests -v --with-timer -w $(pwd) dbas graph admin api export

#function-test:
#  <<: *job-definition
#  stage: test
#  script:
#    - pserve development.ini --daemon
#    - sleep 10
#    - python tests/splinterTests.py --no-input
#  allow_failure: true

acceptance:
  <<: *job-definition
  stage: test
  script:
    - pserve $INIFILE --daemon
    - sleep 10
    - nosetests -v --with-timer --timer-ok 10 --process-timeout=120 tests/test_frontend
