image: hhucn/dbas-build

services:
  - hhucn/docker-dbas-postgres

before_script:
  - export PIP_CACHE_DIR="pip-cache"
  - pip install --quiet -U pip
  - pip install --quiet -r requirements.txt
  - python setup.py --quiet develop
  - initialize_discussion_sql docker.ini > /dev/null 2>&1
  - initialize_news_sql docker.ini > /dev/null 2>&1
  - init_discussion_testvotes docker.ini > /dev/null 2>&1
  - init_review_tests docker.ini > /dev/null 2>&1
  - cp docker.ini development.ini
  - pserve development.ini --daemon

flake8:
  stage: test
  script:
    - pip install --quiet flake8
    - flake8 .
  allow_failure: true

unit-test:
  stage: test
  script:
    - nosetests -v -w $(pwd) dbas graph admin api export

function-test:
  stage: test
  script:
    - python tests/splinterTests.py --no-input
  allow_failure: true

nose-acceptance-tests:
  stage: test
  script:
    - sleep 10
    - nosetests --process-timeout=120 tests/test_frontend
  allow_failure: true # Until the tests are fine remotely
