image: hhucn/python

services:
  - hhucn/docker-dbas-postgres

before_script:
  - pip install -Uq pip
  - pip install -rq requirements.txt
  - python setup.py develop
  - initialize_discussion_sql docker.ini
  - initialize_news_sql docker.ini

test:
  stage: test
  script:
    # - flake8 .
    - cp docker.ini development.ini
    - nosetests --with-coverage --cover-package=api
