image: hhucn/dbas-build

variables:
  INIFILE: "docker.ini"

.job-template: &job-definition
  services:
    - hhucn/docker-dbas-postgres
  before_script:
    - pip install --quiet -U pip
    - pip install --quiet -r requirements.txt
    - python setup.py --quiet develop
    - cp $INIFILE development.ini
    - initialize_discussion_sql $INIFILE > /dev/null 2>&1
    - initialize_news_sql $INIFILE > /dev/null 2>&1
    - init_discussion_testvotes $INIFILE > /dev/null 2>&1
    - init_review_tests $INIFILE > /dev/null 2>&1

start-server:
  <<: *job-definition
  stage: build
  script:
    - uwsgi --ini-paste $INIFILE

flake8:
  stage: build
  script:
    - pip install --quiet flake8
    - flake8 .
  allow_failure: true

jshint:
  stage: build
  script:
    - npm install -g jshint
    - jshint ./dbas/static/js/{main,ajax,discussion,review}/*.js
  allow_failure: true

unit:
  <<: *job-definition
  stage: test
  script:
    - uwsgi --ini-paste $INIFILE
    - nosetests --with-coverage --cover-package=dbas --cover-package=api --cover-package=graph --cover-package=export --cover-package=admin --with-timer -w $(pwd) dbas graph admin api export

acceptance:
  <<: *job-definition
  stage: test
  script:
    - uwsgi --ini-paste $INIFILE
    - nosetests --with-timer --timer-ok 10 --process-timeout=120 tests/test_frontend
