image: docker

stages:
  - build
  - analyze
  - test
  - cleanup

# Stop all running containers after each job, although they were not always started
after_script:
  - docker stop dbas_web_$CI_BUILD_ID dbas_db_$CI_BUILD_ID

# Start Docker containers and wait some time to seed the database
.job-template: &run-server
  variables:
    DB_URL: "db:5432"
    DB_USER: "dbas"
    DB_PW: "gAjOVf8MHBgHwUH8NmyWqwQQ43En1b0Mk1wZbm2JOYzWJ8PrQbwEIoWRhz4zT6Wz"
  before_script:
    - docker run -d --rm --name dbas_db_$CI_BUILD_ID dbas_db_$CI_PIPELINE_ID
    - sleep 10
    - docker run -d --rm --env-file development.env --name dbas_web_$CI_BUILD_ID --link dbas_db_$CI_BUILD_ID:db dbas_web_$CI_PIPELINE_ID


# ------------------------------------------------------------------------------
# Job definitions

build_images:
  stage: build
  script:
    - docker build -t dbas_web_$CI_PIPELINE_ID .
    - docker build -t dbas_db_$CI_PIPELINE_ID docker/db

flake8:
  stage: analyze
  script:
    - apk add --no-cache python3 && python3 -m ensurepip
    - pip3 install --quiet flake8
    - flake8 .
  allow_failure: true

jshint:
  stage: analyze
  script:
    - apk add --no-cache nodejs bash
    - npm install -g jshint
    - bash -c "jshint ./dbas/static/js/{main,ajax,discussion,review,d3}/*.js"
  allow_failure: true

unit:
  <<: *run-server
  stage: test
  script:
    - docker exec dbas_web_$CI_BUILD_ID nosetests --with-coverage --cover-package=dbas --cover-package=api --cover-package=graph --cover-package=export --cover-package=admin --with-timer -w . dbas graph admin api export

acceptance:
  <<: *run-server
  stage: test
  script:
    - docker exec dbas_web_$CI_BUILD_ID nosetests --with-timer --timer-ok 10 --process-timeout=120 tests/test_frontend

cleanup_images:
  stage: cleanup
  script:
    - docker rmi dbas_web_$CI_PIPELINE_ID dbas_db_$CI_PIPELINE_ID
  when: always
