image: docker

stages:
  - build
  - style_guides
  - frontend_test
  - unit_test
  - deploy
  - cleanup

# Start Docker containers and wait some time to seed the database
.job-template: &run-server
  before_script:
    - docker run -d --rm --name dbas_db_$CI_JOB_ID dbas_db_$CI_PIPELINE_ID
    - sleep 10
    - docker run -d --rm --env-file development.env --name dbas_web_$CI_JOB_ID --link dbas_db_$CI_JOB_ID:db dbas_web_$CI_PIPELINE_ID


# ------------------------------------------------------------------------------
# Job definitions

build_images:
  stage: build
  script:
    - docker build -t dbas_web_$CI_PIPELINE_ID .
    - docker build -t dbas_db_$CI_PIPELINE_ID docker/db

flake8:
  stage: style_guides
  script:
    - apk add --no-cache python3 && python3 -m ensurepip
    - pip3 install --quiet flake8
    - flake8 .
  allow_failure: true

jshint:
  stage: style_guides
  script:
    - apk add --no-cache yarn bash
    - yarn global add jshint
    - bash -c "jshint ./dbas/static/js/{main,ajax,discussion,review,d3}/*.js"
    - bash -c "jshint ./admin/static/js/main/*.js"
    - bash -c "jshint ./webhook/static/js/*.js"
  allow_failure: true

acceptance:
  <<: *run-server
  stage: frontend_test
  script:
    - docker exec dbas_web_$CI_JOB_ID nosetests --with-timer --timer-ok 10 --process-timeout=120 tests/test_frontend
    - docker stop dbas_web_$CI_JOB_ID dbas_db_$CI_JOB_ID

dbas:
  <<: *run-server
  stage: unit_test
  script:
    - docker exec dbas_web_$CI_JOB_ID nosetests --with-coverage --cover-package=dbas --cover-package=api --cover-package=graph --cover-package=export --cover-package=admin --cover-xml --with-timer -w . dbas
    - docker cp dbas_web_$CI_JOB_ID:/dbas/coverage.xml .
    - docker stop dbas_web_$CI_JOB_ID dbas_db_$CI_JOB_ID
  coverage: '/^TOTAL\s*\d+\s*\d+\s*(\d+\%)\s*$/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 10 mins

graph:
  <<: *run-server
  stage: unit_test
  script:
    - docker exec dbas_web_$CI_JOB_ID nosetests --with-coverage --cover-package=dbas --cover-package=api --cover-package=graph --cover-package=export --cover-package=admin --cover-xml --with-timer -w . graph
    - docker cp dbas_web_$CI_JOB_ID:/dbas/coverage.xml .
    - docker stop dbas_web_$CI_JOB_ID dbas_db_$CI_JOB_ID
  coverage: '/^TOTAL\s*\d+\s*\d+\s*(\d+\%)\s*$/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 10 mins

admin:
  <<: *run-server
  stage: unit_test
  script:
    - docker exec dbas_web_$CI_JOB_ID nosetests --with-coverage --cover-package=dbas --cover-package=api --cover-package=graph --cover-package=export --cover-package=admin --cover-xml --with-timer -w . admin
    - docker cp dbas_web_$CI_JOB_ID:/dbas/coverage.xml .
    - docker stop dbas_web_$CI_JOB_ID dbas_db_$CI_JOB_ID
  coverage: '/^TOTAL\s*\d+\s*\d+\s*(\d+\%)\s*$/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 10 mins

api:
  <<: *run-server
  stage: unit_test
  script:
    - docker exec dbas_web_$CI_JOB_ID nosetests --with-coverage --cover-package=dbas --cover-package=api --cover-package=graph --cover-package=export --cover-package=admin --cover-xml --with-timer -w . api
    - docker cp dbas_web_$CI_JOB_ID:/dbas/coverage.xml .
    - docker stop dbas_web_$CI_JOB_ID dbas_db_$CI_JOB_ID
  coverage: '/^TOTAL\s*\d+\s*\d+\s*(\d+\%)\s*$/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 10 mins

export:
  <<: *run-server
  stage: unit_test
  script:
    - docker exec dbas_web_$CI_JOB_ID nosetests --with-coverage --cover-package=dbas --cover-package=api --cover-package=graph --cover-package=export --cover-package=admin --cover-xml --with-timer -w . export
    - docker cp dbas_web_$CI_JOB_ID:/dbas/coverage.xml .
    - docker stop dbas_web_$CI_JOB_ID dbas_db_$CI_JOB_ID
  coverage: '/^TOTAL\s*\d+\s*\d+\s*(\d+\%)\s*$/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 10 mins

sonar:
  image: hhucn/sonar-scanner
  stage: deploy
  script:
    - sonar-scanner -D sonar.host.url=https://sonarqube.cs.uni-duesseldorf.de -D sonar.login=$SONARQUBE_LOGIN -D sonar.projectKey=$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME -D sonar.projectName=$CI_PROJECT_NAME -D sonar.projectVersion=1.4 -D sonar.sources=. -D sonar.python.coverage.reportPath=coverage.xml
  only:
    - development
  when: always

deploy_image:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    # Build docs
    - docker build -t $CI_REGISTRY_IMAGE -f Dockerfile.docs .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:docs
    - docker push $CI_REGISTRY_IMAGE:docs
  only:
    - master

deploy_dev_image:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:development
    - docker push $CI_REGISTRY_IMAGE:development
  only:
    - development

cleanup_images:
  stage: cleanup
  script:
    - docker rmi -f dbas_web_$CI_PIPELINE_ID dbas_db_$CI_PIPELINE_ID
  when: always
