image: hhucn/dbas-build

variables:
  INIFILE: "docker.ini"

.job-template: &job-definition
  services:
    - hhucn/docker-dbas-postgres
  before_script:
    - pip install --quiet -U pip
    - pip install --quiet -r requirements.txt
    - python setup.py --quiet develop
    - cp $INIFILE development.ini
    - initialize_discussion_sql $INIFILE > /dev/null 2>&1
    - initialize_news_sql $INIFILE > /dev/null 2>&1
    - init_discussion_testvotes $INIFILE > /dev/null 2>&1
    - init_review_tests $INIFILE > /dev/null 2>&1
  artifacts:
    name: "$CI_BUILD_NAME pserve log"
    paths:
        - ./pserve.log
    when: on_failure

start-server:
  <<: *job-definition
  stage: build
  script:
    - pserve $INIFILE --daemon --log-file pserve.log
    - until (pserve $INIFILE --status &>/dev/null); do echo "Server not up.. waiting" && sleep 1; done
    - pserve $INIFILE --status

flake8:
  stage: build
  script:
    - pip install --quiet flake8
    - flake8 .
  allow_failure: true

unit:
  <<: *job-definition
  stage: test
  script:
    - pserve $INIFILE --daemon --log-file pserve.log
    - until (pserve $INIFILE --status &>/dev/null); do echo "Server not up.. waiting" && sleep 1; done
    - nosetests --with-timer -w $(pwd) dbas graph admin api export

acceptance:
  <<: *job-definition
  stage: test
  script:
    - pserve $INIFILE --daemon --log-file pserve.log
    - until (pserve $INIFILE --status &>/dev/null); do echo "Server not up.. waiting" && sleep 1; done
    - nosetests --with-timer --timer-ok 10 --process-timeout=120 tests/test_frontend
