version: "3.2"
services:
  db:
    build: docker/db/
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/entrypoint:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/postgresql/data
    tmpfs: /tmp

  web:
    image: gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/dbas
    command: bash -c "sleep 10 && uwsgi --ini-paste production.ini"
    restart: always
    ports:
      - "4284:4284"
    links:
      - db:db
    env_file:
      - production.env
    depends_on:
      - db
    tmpfs: /tmp