version: '2'
services:
  db:
    build: docker/database/
    ports:
      - "5433:5432"
  web:
    build: .
    command: /bin/bash core/docker_init.sh
    volumes:
      - .:/code
    ports:
      - "80:80"
    links:
      - db:db