version: "3.2"
services:
  db:
    build: docker/db/
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/entrypoint:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/postgresql/data
    tmpfs: /tmp

  web:
    image: gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/dbas
    command: bash -c "sleep 10 && alembic upgrade head && uwsgi --ini-paste production.ini"
    restart: always
    ports:
      - "4284:4284"
    environment:
      AUTHN_SECRET: ${AUTHN_SECRET}
      DB_PW: ${DB_PW}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      URL: ${URL}
    env_file:
      - production.env
    tmpfs: /tmp
