version: "3.1"
services:
  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - ./postgres_db:/var/lib/postgresql/data
    tmpfs: /tmp

  notifications:
    image: hhucn/dbas-notifications
    restart: always
    ports:
      - "5222:5222"
    volumes:
      - /etc/letsencrypt:/cert:ro

  docs:
    image: gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/dbas:docs
    restart: always
    ports:
      - "8000:8000"
    tmpfs: /tmp

  web:
    image: gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/dbas
    command: bash -c "sleep 10 && uwsgi --ini-paste production.ini"
    restart: always
    ports:
      - "4284:4284"
    links:
      - db:db
    env_file:
      - production.env
    depends_on:
      - db
    tmpfs: /tmp
