version: "3.2"
services:
  db:
    build: docker/db/
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/entrypoint:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DB_PW}
    tmpfs: /tmp

  web:
    build: .
    command: bash -c "sleep 8 && alembic upgrade head && pserve development.ini --reload"
    volumes:
    - .:/dbas:delegated
    ports:
      - "4284:4284"
    environment:
      AUTHN_SECRET: ${AUTHN_SECRET}
      DB_PW: ${DB_PW}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      URL: ${URL}
    tmpfs: /tmp
