version: '2'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    tmpfs: /tmp
    env_file: # Needed in 001_init.sh
      - development.env
  notifications:
    image: gitlab.cs.uni-duesseldorf.de:5001/dbas/notifications
    ports:
      - "5222:5222"
    tmpfs: /tmp
  web:
    build: .
    command: bash -c "sleep 8 && pserve development.ini --reload"
    restart: always
    volumes:
      - .:/dbas
    ports:
      - "4284:4284"
    links:
      - db:db
    env_file:
      - development.env
    depends_on:
      - db
    tmpfs: /tmp
