version: '2'
services:
  db:
    image: hhucn/docker-dbas-postgres
  web:
    build: .
    command: /bin/bash docker_init.sh
    volumes:
      - .:/code
    ports:
      - "4284:4284"
    links:
      - db:hhucn__docker-dbas-postgres
    tmpfs: /tmp