version: "3.2"
services:
  search:
    image: gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/search:development
    restart: on-failure
    ports:
      - "9200:9200"
      - "5000:5000"
    environment:
      APPLICATION_HOST: web
      APPLICATION_PORT: 4284
      APPLICATION_PROTOCOL: http
      DATABASE_NAME: discussion
      DATABASE_PASSWORD: ${DB_PW}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USER}