version: '2'
services:
  notifications:
    volumes:
      - /etc/letsencrypt:/cert:ro
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - "8000:8000"
    tmpfs: /tmp
  web:
    command: uwsgi --ini-paste production.ini
