version: '2'
services:
  notifications:
    volumes:
      - /etc/letsencrypt:/cert:ro
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - "8000:8000"
    tmpfs: /tmp
  web:
    image: gitlab.cs.uni-duesseldorf.de:5001/dbas/dbas
    command: bash -c "sleep 10 && uwsgi --ini-paste production.ini"
