version: "3.2"
services:
  search:
    image: hhucn/dbas-search:develop
    ports:
      - "9200:9200"
      - "5000:5000"
    environment:
      APPLICATION_HOST: web
      APPLICATION_PORT: 4284
      APPLICATION_PROTOCOL: http
      DATABASE_NAME: discussion
      DATABASE_PASSWORD: ${DB_PW}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USER}