version: '2'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    tmpfs: /tmp
  notifications:
    image: hhucn/dbas-notifications
    ports:
      - "5222:5222"
    tmpfs: /tmp
  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "4284:4284"
    links:
      - db:db
    depends_on:
      - db
    tmpfs: /tmp
