version: "3.2"
services:
  db:
    image: gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/dbas/db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/entrypoint:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/postgresql/data
    tmpfs: /tmp

  web:
    image: gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/dbas
    command: bash -c "./wait-for-it.sh -t 0 -h db -p 5432 && alembic upgrade head && uwsgi --ini-paste production.ini"
    restart: unless-stopped
    environment:
      AUTHN_SECRET: ${AUTHN_SECRET}
      DB_PW: ${DB_PW}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      URL: ${URL}
      KEY_PATH: ${KEY_PATH}
      PUBKEY_PATH: ${PUBKEY_PATH}
    # env_file:  # Optional if you want to change passwords
    #  - production.env
    tmpfs: /tmp

  docs:
    image: gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/dbas/docs
    restart: unless-stopped

  proxy:
    image: nginx:1.18-alpine
    ports:
      - "${PROXY_PORT}:80"
    environment:
      DEPLOY_HOST: ${URL}
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/domain.conf:/etc/nginx/domain.conf:ro
      - ./nginx/init:/etc/nginx/init:ro
    restart: unless-stopped
